import assert from "node:assert/strict";
import { test } from "node:test";

/**
 * The revise action shares its custom-ID codec with approve/reject, so the
 * round-trip has to keep working for all three -- a decode that silently
 * returns null turns a button into a no-op with no error anywhere.
 */

const { encodeCustomId, decodeCustomId } = await import("../src/approval.ts");
const { sessionIdFromPrBody } = await import("../src/naming.ts");

test("every approval action round-trips through the custom ID", () => {
  for (const action of ["approve", "reject", "revise"] as const) {
    for (const issueNumber of [7, null]) {
      const encoded = encodeCustomId({ action, prNumber: 11, issueNumber });
      assert.ok(encoded.length <= 100, "Discord caps custom IDs at 100 chars");
      assert.deepEqual(decodeCustomId(encoded), { action, prNumber: 11, issueNumber });
    }
  }
});

test("unknown actions are rejected rather than defaulting to something", () => {
  assert.equal(decodeCustomId("eous:deploy:1:2"), null);
  assert.equal(decodeCustomId("eous:approve:x:2"), null);
});

test("session id is recoverable from a PR body", () => {
  const body = [
    "Some summary text.",
    "",
    "---",
    "",
    "Closes #7",
    "",
    "Generated by EousBot (`22` turns, $0.823). Typecheck and tests passed.",
    "",
    "Agent session `0199aa11-bb22-cc33-dd44-ee55ff667788`.",
  ].join("\n");

  assert.equal(sessionIdFromPrBody(body), "0199aa11-bb22-cc33-dd44-ee55ff667788");
});

test("a PR body without a session id yields null, not a crash", () => {
  assert.equal(sessionIdFromPrBody("no session here"), null);
  assert.equal(sessionIdFromPrBody(null), null);
  assert.equal(sessionIdFromPrBody(undefined), null);
});
